name: Update GitHub Profile README

on:
  push:
    branches:
      - main   # তুমি push দিলে তবেই run হবে
  workflow_dispatch:   # চাইলে manual run করতে পারবা

jobs:
  update-readme:
    runs-on: ubuntu-latest

    permissions:
      contents: write   # push করার জন্য দরকার

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Contribution Graph
        uses: Ashutosh00710/github-readme-activity-graph@main
        with:
          username: Sheikh-Rabby
          theme: react-dark
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and Push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update activity graph" || echo "No changes to commit"
          git push
